builders:
  obfuscate:
    import: "package:flutter_neo_shield/src/string_shield/generator/builder.dart"
    builder_factories: ["obfuscateBuilder"]
    build_extensions: {".dart": [".obfuscate.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
