import '../scan_rule.dart';
import '../severity.dart';

const _cat = 'Hardcoded Secrets';

/// Rules for detecting hardcoded secrets in source code.
List<ScanRule> hardcodedSecretsRules() => [
      // 1. API Keys
      ScanRule(
        id: 'SEC001',
        category: _cat,
        severity: Severity.critical,
        title: 'Hardcoded API key detected',
        description:
            'API keys (sk_live_, pk_test_, AKIA, AIza, ghp_, glpat-, xox) found in source code.',
        recommendation:
            'Move API keys to environment variables or use StringShield obfuscation.',
        pattern: RegExp(
          r'''(?:['"`])?(sk_live_[A-Za-z0-9]{20,}|pk_test_[A-Za-z0-9]{20,}|pk_live_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z\-_]{35}|ghp_[A-Za-z0-9]{36}|gho_[A-Za-z0-9]{36}|glpat-[A-Za-z0-9\-]{20,}|xox[bpas]-[A-Za-z0-9\-]{10,})(?:['"`])?''',
        ),
        fileExtensions: ['.dart', '.yaml', '.json', '.env', '.properties'],
        exclusions: [
          RegExp(r'//\s*example'),
          RegExp(r'test[/\\]'),
          RegExp(r'_test\.dart$'),
        ],
      ),

      // 2. OAuth / Bearer Tokens
      ScanRule(
        id: 'SEC002',
        category: _cat,
        severity: Severity.critical,
        title: 'Hardcoded OAuth/Bearer token',
        description:
            'Bearer token or OAuth secret found hardcoded in source code.',
        recommendation:
            'Use secure storage or environment variables for tokens.',
        pattern: RegExp(
          r'''['"`]Bearer\s+[A-Za-z0-9_\-./+=]{20,}['"`]''',
          caseSensitive: false,
        ),
        fileExtensions: ['.dart', '.yaml', '.json'],
      ),

      // 3. JWT Tokens
      ScanRule(
        id: 'SEC003',
        category: _cat,
        severity: Severity.critical,
        title: 'Hardcoded JWT token',
        description: 'JWT token (eyJ...) found embedded in source code.',
        recommendation:
            'Never hardcode JWT tokens. Fetch them at runtime from a secure backend.',
        pattern: RegExp(
          r'''['"`]eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_\-+=]{10,}['"`]''',
        ),
        fileExtensions: ['.dart', '.json'],
      ),

      // 4. Private Keys (PEM)
      ScanRule(
        id: 'SEC004',
        category: _cat,
        severity: Severity.critical,
        title: 'Private key material detected',
        description:
            'PEM-encoded private key found in source. RSA/EC/DSA private keys must never be in code.',
        recommendation:
            'Store private keys in platform keystore/keychain via SecureStorageShield.',
        pattern: RegExp(
          r'-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----',
        ),
        fileExtensions: ['.dart', '.pem', '.key', '.txt', '.json', '.yaml'],
      ),

      // 5. Database Connection Strings
      ScanRule(
        id: 'SEC005',
        category: _cat,
        severity: Severity.critical,
        title: 'Database connection string detected',
        description:
            'Database URI with credentials found (mongodb://, postgres://, mysql://, redis://).',
        recommendation:
            'Use environment variables or encrypted config for database URIs.',
        pattern: RegExp(
          r'''['"`](mongodb(\+srv)?|postgres(ql)?|mysql|redis|amqp)://[^'"`\s]{10,}['"`]''',
          caseSensitive: false,
        ),
        fileExtensions: ['.dart', '.yaml', '.json', '.env', '.properties'],
      ),

      // 6. Firebase Credentials
      ScanRule(
        id: 'SEC006',
        category: _cat,
        severity: Severity.high,
        title: 'Firebase credentials in source',
        description:
            'Firebase config values (API key, project ID, app ID) found in Dart source code.',
        recommendation:
            'Use firebase_options.dart generated by FlutterFire CLI and exclude from version control, or use StringShield.',
        pattern: RegExp(
          r'''(firebaseConfig|apiKey|messagingSenderId|appId|measurementId)\s*[:=]\s*['"`][A-Za-z0-9_\-:]{10,}['"`]''',
        ),
        fileExtensions: ['.dart', '.js', '.json'],
        exclusions: [
          RegExp(r'firebase_options\.dart$'),
        ],
      ),

      // 7. Cloud Provider Keys
      ScanRule(
        id: 'SEC007',
        category: _cat,
        severity: Severity.critical,
        title: 'Cloud provider credentials detected',
        description:
            'AWS, GCP, or Azure credentials found hardcoded in source.',
        recommendation:
            'Use IAM roles, service accounts, or environment variables.',
        pattern: RegExp(
          r'''(DefaultEndpointsProtocol=https|AccountKey=[A-Za-z0-9+/=]{40,}|aws_secret_access_key\s*=\s*[A-Za-z0-9/+=]{30,}|AZURE_[A-Z_]+\s*=\s*['"`][^'"`]{10,}['"`])''',
          caseSensitive: false,
        ),
        fileExtensions: ['.dart', '.yaml', '.json', '.env', '.properties'],
        exclusions: [
          RegExp(r'cli_scanner'),
        ],
      ),

      // 8. Webhook URLs
      ScanRule(
        id: 'SEC008',
        category: _cat,
        severity: Severity.high,
        title: 'Webhook URL detected',
        description:
            'Slack, Discord, or Stripe webhook URL found in source code.',
        recommendation:
            'Store webhook URLs in environment variables or encrypted config.',
        pattern: RegExp(
          r'''['"`](https://hooks\.slack\.com/services/[A-Za-z0-9/]+|https://discord(app)?\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+|https://api\.stripe\.com/[A-Za-z0-9/]+)['"`]''',
        ),
        fileExtensions: ['.dart', '.yaml', '.json', '.env'],
      ),

      // 9. Hardcoded Encryption Keys/IVs
      ScanRule(
        id: 'SEC009',
        category: _cat,
        severity: Severity.critical,
        title: 'Hardcoded encryption key or IV',
        description:
            'Encryption key or initialization vector appears to be hardcoded.',
        recommendation:
            'Generate keys at runtime using EncryptionShield.generateKey() and store in SecureStorageShield.',
        pattern: RegExp(
          r'''(encryption[_]?key|secret[_]?key|aes[_]?key|iv|nonce|init[_]?vector)\s*[:=]\s*['"`][A-Za-z0-9+/=]{16,}['"`]''',
          caseSensitive: false,
        ),
        fileExtensions: ['.dart', '.yaml', '.json'],
      ),

      // 10. Password Strings
      ScanRule(
        id: 'SEC010',
        category: _cat,
        severity: Severity.critical,
        title: 'Hardcoded password or PIN',
        description:
            'Password, secret, or PIN value found hardcoded in source code.',
        recommendation:
            'Never hardcode passwords. Use SecureStorageShield or prompt the user.',
        pattern: RegExp(
          r'''(password|passwd|pwd|pin_code|passphrase|master_key)\s*[:=]\s*['"`][^'"`]{3,}['"`]''',
          caseSensitive: false,
        ),
        fileExtensions: ['.dart', '.yaml', '.json', '.env', '.properties'],
        exclusions: [
          RegExp(r'_test\.dart$'),
          RegExp(r"""password\s*[:=]\s*['"`]\$"""),
          RegExp(r'obscureText\s*:\s*true'),
          RegExp(r'labelText.*[Pp]assword'),
          RegExp(r'hintText.*[Pp]assword'),
          RegExp(r'TextFormField'),
          RegExp(r'TextField'),
        ],
      ),

      // 11. SSH Keys
      ScanRule(
        id: 'SEC011',
        category: _cat,
        severity: Severity.high,
        title: 'SSH private key reference',
        description: 'SSH private key file path or content detected.',
        recommendation:
            'Remove SSH keys from source. Use CI/CD secrets or deploy keys.',
        pattern: RegExp(
          r'(-----BEGIN OPENSSH PRIVATE KEY-----|id_rsa|id_ed25519|id_ecdsa)\b',
        ),
        fileExtensions: ['.dart', '.yaml', '.json', '.sh', '.env'],
        exclusions: [
          RegExp(r'\.pub\b'),
          RegExp(r'//.*known_hosts'),
          RegExp(r'cli_scanner'),
        ],
      ),

      // 12. CI/CD Tokens
      ScanRule(
        id: 'SEC012',
        category: _cat,
        severity: Severity.critical,
        title: 'CI/CD token detected',
        description:
            'CircleCI, GitHub Actions, Bitrise, or other CI/CD token found in source.',
        recommendation: 'Use CI/CD platform secret management.',
        pattern: RegExp(
          r'''(CIRCLECI_TOKEN|GITHUB_TOKEN|BITRISE_API_KEY|TRAVIS_TOKEN|CODECOV_TOKEN|SONAR_TOKEN)\s*[:=]\s*['"`]?[A-Za-z0-9_\-]{10,}['"`]?''',
        ),
        fileExtensions: [
          '.dart',
          '.yaml',
          '.yml',
          '.json',
          '.env',
          '.sh',
          '.properties'
        ],
      ),
    ];
